# Generated by Django 5.1.2 on 2024-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=100, null=True)),
                ('p_mrp', models.CharField(blank=True, max_length=100, null=True)),
                ('p_quan', models.CharField(blank=True, max_length=100, null=True)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('p_desc', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
