# Generated by Django 5.1.2 on 2024-10-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0002_product_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='p_img1',
            field=models.ImageField(blank=True, null=True, upload_to='Products'),
        ),
    ]
