# Generated by Django 5.1.2 on 2024-10-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0003_product_db_p_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='cat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
